// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRRBmTHiNSWRe2T2mLm4CRDAGFIWsbyF4',
    appId: '1:347616233725:web:613b07fb42c9c535cf9694',
    messagingSenderId: '347616233725',
    projectId: 'tagramm-52a7d',
    authDomain: 'tagramm-52a7d.firebaseapp.com',
    storageBucket: 'tagramm-52a7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfNPhieBZF9WGJJrBVKe2YgxjUqHtVUnY',
    appId: '1:347616233725:android:3480dd000215ac98cf9694',
    messagingSenderId: '347616233725',
    projectId: 'tagramm-52a7d',
    storageBucket: 'tagramm-52a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_QOV-oZBXAkqBAEVWaWgYui60uXY6GU',
    appId: '1:347616233725:ios:3bfca52d6c9ad1ffcf9694',
    messagingSenderId: '347616233725',
    projectId: 'tagramm-52a7d',
    storageBucket: 'tagramm-52a7d.appspot.com',
    iosClientId: '347616233725-1alg4cu2ldhr4dfq2ue37o6keb9vf7n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagramm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_QOV-oZBXAkqBAEVWaWgYui60uXY6GU',
    appId: '1:347616233725:ios:3bfca52d6c9ad1ffcf9694',
    messagingSenderId: '347616233725',
    projectId: 'tagramm-52a7d',
    storageBucket: 'tagramm-52a7d.appspot.com',
    iosClientId: '347616233725-1alg4cu2ldhr4dfq2ue37o6keb9vf7n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tagramm',
  );
}
